name: 5-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Proposals revalidations
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/revalidate?type=proposals' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
