name: refunds-other-cron
on:
  schedule:
    - cron: '* */4 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Governance refunds - gov
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-refunds?filterType=gov' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: Governance refunds - oracles
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-refunds?filterType=oracles' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'  
      - name: Governance refunds - multidelegator
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-refunds?filterType=multidelegator' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: Governance refunds - gnosis
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-refunds?filterType=gnosis' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'    
      - name: Governance refunds - other
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-refunds?filterType=other' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'    