name: 12-h-cron
on:
  schedule:
    - cron: '* */12 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Positions
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-positions' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
      - name: Bad debt
        run: |
          curl -v --request GET \
          --url 'https://www.inverse.finance/api/transparency/repayments-v2'          
